CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "GoogleId" text NOT NULL,
    "ProfilePictureUrl" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "IsSuspended" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "RefreshTokens" (
    "RefreshTokenId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "JwtTokenId" text NOT NULL,
    "Refresh_Token" text NOT NULL,
    "IsValid" boolean NOT NULL,
    "IsUsed" boolean NOT NULL,
    "ExpireDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("RefreshTokenId")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "IX_AspNetUsers_UserName" ON "AspNetUsers" ("UserName");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260625075809_Initial', '10.0.9');

COMMIT;

START TRANSACTION;
CREATE TABLE "Listings" (
    "Id" uuid NOT NULL,
    "Type" integer NOT NULL,
    "Title" character varying(255) NOT NULL,
    "TitleAm" character varying(255),
    "Organization" character varying(255) NOT NULL,
    "CountryCode" character varying(5) NOT NULL,
    "Description" text NOT NULL,
    "DescriptionAm" text,
    "ApplyUrl" text NOT NULL,
    "Deadline" date,
    "IsActive" boolean NOT NULL,
    "IsFeatured" boolean NOT NULL,
    "Source" character varying(100),
    "JobCategory" integer,
    "SalaryMin" integer,
    "SalaryMax" integer,
    "EmploymentType" integer,
    "MinExperienceYears" integer,
    "ScholarshipField" integer,
    "DegreeLevel" integer,
    "FundingType" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Listings" PRIMARY KEY ("Id")
);

CREATE TABLE "UserProfiles" (
    "Id" uuid NOT NULL,
    "UserId" text NOT NULL,
    "SeekingType" integer NOT NULL,
    "TargetCountries" text[] NOT NULL,
    "PreferredJobCategories" integer[] NOT NULL,
    "PreferredScholarshipFields" integer[] NOT NULL,
    "TargetDegreeLevel" integer,
    "EducationLevel" integer NOT NULL,
    "WorkExperienceYears" smallint NOT NULL,
    "EnglishLevel" character varying(10),
    "CvFileUrl" text,
    "CvUploadedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserProfiles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserProfiles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Listings_Deadline" ON "Listings" ("Deadline");

CREATE INDEX "IX_Listings_IsFeatured" ON "Listings" ("IsFeatured");

CREATE INDEX "IX_Listings_JobCategory" ON "Listings" ("JobCategory");

CREATE INDEX "IX_Listings_ScholarshipField" ON "Listings" ("ScholarshipField");

CREATE INDEX "IX_Listings_Type_CountryCode_IsActive" ON "Listings" ("Type", "CountryCode", "IsActive");

CREATE UNIQUE INDEX "IX_UserProfiles_UserId" ON "UserProfiles" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260626203722_model added', '10.0.9');

COMMIT;

START TRANSACTION;
CREATE TABLE "Bookmarks" (
    "Id" uuid NOT NULL,
    "UserId" text NOT NULL,
    "ListingId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Bookmarks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Bookmarks_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Bookmarks_Listings_ListingId" FOREIGN KEY ("ListingId") REFERENCES "Listings" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserApplications" (
    "Id" uuid NOT NULL,
    "UserId" text NOT NULL,
    "ListingId" uuid NOT NULL,
    "Status" integer NOT NULL,
    "Notes" text,
    "AppliedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserApplications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserApplications_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserApplications_Listings_ListingId" FOREIGN KEY ("ListingId") REFERENCES "Listings" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Bookmarks_ListingId" ON "Bookmarks" ("ListingId");

CREATE UNIQUE INDEX "IX_Bookmarks_UserId_ListingId" ON "Bookmarks" ("UserId", "ListingId");

CREATE INDEX "IX_UserApplications_ListingId" ON "UserApplications" ("ListingId");

CREATE UNIQUE INDEX "IX_UserApplications_UserId_ListingId" ON "UserApplications" ("UserId", "ListingId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260627110606_Bookmark added', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "UserProfiles" ALTER COLUMN "UserId" DROP NOT NULL;

ALTER TABLE "UserProfiles" ALTER COLUMN "TargetCountries" DROP NOT NULL;

ALTER TABLE "UserProfiles" ALTER COLUMN "PreferredScholarshipFields" DROP NOT NULL;

ALTER TABLE "UserProfiles" ALTER COLUMN "PreferredJobCategories" DROP NOT NULL;

ALTER TABLE "UserApplications" ALTER COLUMN "UserId" DROP NOT NULL;

ALTER TABLE "RefreshTokens" ALTER COLUMN "UserId" DROP NOT NULL;

ALTER TABLE "RefreshTokens" ALTER COLUMN "Refresh_Token" DROP NOT NULL;

ALTER TABLE "RefreshTokens" ALTER COLUMN "JwtTokenId" DROP NOT NULL;

ALTER TABLE "Listings" ALTER COLUMN "Title" DROP NOT NULL;

ALTER TABLE "Listings" ALTER COLUMN "Organization" DROP NOT NULL;

ALTER TABLE "Listings" ALTER COLUMN "Description" DROP NOT NULL;

ALTER TABLE "Listings" ALTER COLUMN "CountryCode" DROP NOT NULL;

ALTER TABLE "Listings" ALTER COLUMN "ApplyUrl" DROP NOT NULL;

ALTER TABLE "Bookmarks" ALTER COLUMN "UserId" DROP NOT NULL;

ALTER TABLE "AspNetUsers" ALTER COLUMN "ProfilePictureUrl" DROP NOT NULL;

ALTER TABLE "AspNetUsers" ALTER COLUMN "LoginProvider" DROP NOT NULL;

ALTER TABLE "AspNetUsers" ALTER COLUMN "LastName" DROP NOT NULL;

ALTER TABLE "AspNetUsers" ALTER COLUMN "GoogleId" DROP NOT NULL;

ALTER TABLE "AspNetUsers" ALTER COLUMN "FirstName" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260629171603_applicationuser_fields_nullable', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "UserProfiles" ADD "DateOfBirth" date;

ALTER TABLE "UserProfiles" ADD "PassportStatus" integer;

ALTER TABLE "UserProfiles" ADD "Sex" integer;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260630065017_UserProfileUpdate', '10.0.9');

COMMIT;

START TRANSACTION;
CREATE TABLE "Payments" (
    "Id" uuid NOT NULL,
    "UserId" text,
    "TxRef" character varying(100) NOT NULL,
    "ChapaReference" text,
    "Tier" integer NOT NULL,
    "AmountEtb" integer NOT NULL,
    "Status" integer NOT NULL,
    "Provider" integer NOT NULL,
    "SubscriptionId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CompletedAt" timestamp with time zone,
    CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Payments_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Subscriptions" (
    "Id" uuid NOT NULL,
    "UserId" text,
    "Tier" integer NOT NULL,
    "Status" integer NOT NULL,
    "StartedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "CancelledAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Subscriptions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Subscriptions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Payments_TxRef" ON "Payments" ("TxRef");

CREATE INDEX "IX_Payments_UserId" ON "Payments" ("UserId");

CREATE INDEX "IX_Subscriptions_UserId_Status_ExpiresAt" ON "Subscriptions" ("UserId", "Status", "ExpiresAt");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260630124007_subscriptionmodel', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUsers" ADD "SubscriptionTier" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260630203021_subscriptiontier_added_user', '10.0.9');

COMMIT;

START TRANSACTION;
CREATE TABLE "UserDocuments" (
    "Id" uuid NOT NULL,
    "UserId" text,
    "Type" integer NOT NULL,
    "FileName" character varying(255),
    "StorageKey" character varying(500),
    "FileSizeBytes" bigint NOT NULL,
    "ContentType" text,
    "UploadedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserDocuments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserDocuments_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_UserDocuments_UserId" ON "UserDocuments" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260704102952_userdocument', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "UserProfiles" ADD "ExperienceRange" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260708131407_ExperienceRange_Added', '10.0.9');

COMMIT;

